INSERT INTO `badge` (id, name, `type`, slug, description, multiple, awarded_count)
VALUES
(1, 'Disciplinado', 3, 'disciplinado', 'Borró su propio posteo con 3 o más votos positivos', 1, 0),
(2, 'Presión Grupal', 3, 'presion-grupal', 'Borró su propio posteo con 3 o más votos negativos', 1, 0),
(3, 'Respuesta Aceptable', 3, 'respuesta-aceptable', 'Respuesta con 10 votos positivos', 1, 0),
(4, 'Solicitud Aceptable', 3, 'solicitud-aceptable', 'Solicitud con 10 votos positivos', 1, 0),
(5, 'Sabio', 3, 'sabio', 'Dejó 10 comentarios con puntaje de 10 o más', 0, 0),
(6, 'Solicitud Popular', 3, 'solicitud-popular', 'Hizo una solicitud con 1,000 vistas', 1, 0),
(7, 'Patrulla Ciudadana', 3, 'patrulla-ciudadana', 'Primer post marcado como ofensivo', 0, 0),
(8, 'Limpieza', 3, 'limpieza', 'Primer rollback', 0, 0),
(9, 'Crítico', 3, 'critico', 'Primer voto negativo', 0, 0),
(10, 'Editor', 3, 'editor', 'Primera edición', 0, 0),
(11, 'Organizador', 3, 'organizador', 'Primer re-etiquetado', 0, 0),
(12, 'Escolar', 3, 'escolar', 'Primera respuesta aceptada en una solicitud de otro', 0, 0),
(13, 'Estudiante', 3, 'estudiante', 'Hizo su primera solicitud con por lo menos un voto positivo', 0, 0),
(14, 'Apoyo', 3, 'apoyo', 'Primer voto positivo', 0, 0),
(15, 'Profesor', 3, 'profesor', 'Primera solicitud respondida con al menos un voto positivo', 0, 0),
(16, 'Autobiógrafo', 3, 'autobiografo', 'Completó todos los datos de su perfil', 0, 0),
(17, 'Auto-didacta', 3, 'auto-didacta', 'Respondió a su propia solicitud con al menos 3 votos positivos', 1, 0),
(18, 'Gran Respuesta', 1, 'gran-respuesta', 'Respuesta con 100 votos positivos', 1, 0),
(19, 'Gran Solicitud', 1, 'gran-solicitud', 'Solicitud con 100 votos positivos', 1, 0),
(20, 'Solicitud Estelar', 1, 'solicitud-estelar', 'Solicitud favorita de 100 usuarios', 1, 0),
(21, 'Solicitud Famosa', 1, 'solicitud-famosa', 'Hizo una solicitud con 10,000 vistas', 1, 0),
(22, 'alpha', 2, 'alpha', 'Participó activamente en las pruebas privadas ''alpha''', 0, 0),
(23, 'Buena Respuesta', 2, 'buena-respuesta', 'Respuesta con 25 votos positivos', 1, 0),
(24, 'Buena Solicitud', 2, 'buena-solicitud', 'Solicitud con 25 votos positivos', 1, 0),
(25, 'Solicitud Favorita', 2, 'solicitud-favorita', 'Solicitud favorita de 25 usuarios', 1, 0),
(26, 'Deber Cívico', 2, 'deber-civico', 'Voto 300 veces', 0, 0),
(27, 'Strunk & White', 2, 'strunk-and-white', 'Editó 100 entradas', 0, 0),
(28, 'Generalista', 2, 'generalista', 'Activo en diferentes etiquetas', 0, 0),
(29, 'Experto', 2, 'exporto', 'Extremadamente activo en una etiqueta', 0, 0),
(30, 'Yearling', 2, 'yearling', 'Miembro activo durante un año', 0, 0),
(31, 'Solicitud Notable', 2, 'solicitud-notable', 'Hizo una solicitud con más de 2,500 vistas', 1, 0),
(32, 'Iluminado', 2, 'iluminado', 'Primera respuesta aceptada con al menos 10 votos positivos', 0, 0),
(33, 'beta', 2, 'beta', 'Participó activamente en las pruebas privadas ''beta''', 0, 0),
(34, 'Guru', 2, 'guru', 'Respuesta aceptada y con 40 votos positivos', 1, 0),
(35, 'Nigromante', 2, 'nigromante', 'Respondió a una solicitud de hace 60 días con al menos 5 votos', 1, 0),
(36, 'Taxónomo', 2, 'taxonomo', 'Creó una etiqueta utilizada por 50 solicitudes', 1, 0);
